version: '3'
services:
  vault:
    container_name: vault
    image: hashicorp/vault:latest #feel free to use latest version since there is not latest tag
    ports:
      - 8200:8200 #expose port 8200 to host
    volumes:
      - VAULT_DATA:/vault/data #mount volume to persist data
      - ./registry_configs:/etc/nginx/conf.d
      - ./vault_config/vault-config.json:/vault/config/vault.json #mount vault config file
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
    cap_add:
      #add capabilities to container
      - IPC_LOCK #allow vault to lock memory
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - devops_network #network to communicate with other services

  docker-registry:
    container_name: registry
    image: registry:2
    volumes:
      - REGISTRY_DATA:/var/lib/registry #mount volume to persist data
    networks:
      - devops_network #network to communicate with other services

  nginx-reverse-proxy:
    container_name: nginx
    image: "nginx:alpine"
    ports:
      - 80:80
      # - 443:443 - uncomment if you want to use SSL
    volumes:
      - ./nginx_config/auth:/etc/nginx/conf.d # Mount the htpasswd file
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      # - ./registry-configs/registry-certificate.pem:/etc/nginx/docker-registry.pem # Mount the SSL certificate file
      # - ./registry-configs/registry-key.pem:/etc/nginx/docker-registry.pem # Mount the SSL private key file
    networks:
      - devops_network

networks:
  devops_network:


volumes:
  VAULT_DATA:
  REGISTRY_DATA:
