---
# - hosts: "app_north_virginia_lex_dev"
# - hosts: all #"{{ deploy_host_name }}"
#   become: yes
#   strategy: free
#   # vars_files:
#   #   - "vars/main.yml"
#   roles:
#     - role: deploy-credential
#       tags: [deploy-credential]
#     - role: deploy-schema
#       tags: [deploy-schema]
#     - role: deploy-identity
#       tags: [deploy-identity]

- hosts: all
  become: true
  roles:
    - docker
- hosts: manager
  become: true
  roles:
    - swarm_manager 
- hosts: worker
  become: true
  roles:
    - swarm_worker

