---
- name: Get private key from Vault
  ansible.builtin.shell: |
    curl -s -H "X-Vault-Token: {{ lookup('env', 'VAULT_TOKEN') }}" \
      {{ lookup('env', 'http://vault') }}/v1/secret/data/path/to/secret | \
      jq -r '.data.data.private_key' > /tmp/private_key.pem

- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- include_tasks: swarm_init.yml
  tags: swarm_init

- include_tasks: create_overlay.yml
  tags: create_overlay
